# Generated by Django 4.2 on 2025-10-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_studentprofile_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='users_sp_assess_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='users_sp_admit_idx',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='assessment_number',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
