# Generated by Django 4.2 on 2025-11-14 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_registrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('peak', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=128)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this announcement was created'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If True, shown on landing page'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(blank=True, help_text='Full announcement text'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.PositiveSmallIntegerField(default=100, help_text='Lower numbers shown first (1-100 recommended)'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text='Brief announcement title', max_length=140),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='address',
            field=models.TextField(blank=True, help_text='Postal address'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='agree',
            field=models.BooleanField(default=False, help_text='Agreed to registration terms'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='birth_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Birth day (1-31)', null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='birth_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Birth month (1-12)', null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Birth year (YYYY)', null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='country_code',
            field=models.CharField(blank=True, help_text='Phone number country code (e.g., +1)', max_length=8),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this request was submitted'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='email',
            field=models.EmailField(help_text='Email address for account creation and contact', max_length=254),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='first_name',
            field=models.CharField(help_text='Given name', max_length=150),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='heard_about',
            field=models.CharField(blank=True, help_text='How the applicant heard about us', max_length=255),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='last_name',
            field=models.CharField(blank=True, help_text='Family name', max_length=150),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes about this request'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number without country code', max_length=32),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', help_text='Current status of this request', max_length=32),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent')], help_text='Type of user account requested', max_length=16),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique admission number, auto-generated if not provided', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='assessment_number',
            field=models.CharField(blank=True, db_index=True, help_text="Student's assessment tracking number", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('principal', 'Principal'), ('teacher', 'Teacher'), ('student', 'Student'), ('account', 'Account')], default='student', help_text="User's role determines their permissions", max_length=32),
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['status', '-created_at'], name='users_regis_status_cd0fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['user_type', 'status'], name='users_regis_user_ty_d67e98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('identifier', 'date')},
        ),
    ]
